name: 'comment-pr'
branding:
  icon: 'message-square'
  color: 'gray-dark'
description: 'Post a dynamic comment on github PullRequests'
inputs:
  comment:  # id of input
    description: 'Comment you would like to post'
    required: true
    default: ''
  GITHUB_TOKEN:
    description: 'Github Token for authentication'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
