name: Test Comments

on: [pull_request]

jobs:
  test:
    name: Test Comment
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Regular Comment
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment: 'This PR is the bees knees!'

  test-json:
    name: Test Json
    permissions: 
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set output
        id: set
        run: |
          echo ::set-output name=theJson::$(cat ./test-assets/test.json)

      - name: Test JSON Comment 1
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          json: ${{steps.set.outputs.theJson}}

      - name: Test JSON Commment 2
        uses: ./
        with:
          json: '{ "this": "pr", "is": "the", "bees": "knees"}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
