name: Test Comments

on: [pull_request]

jobs:
  test:
    name: Test Comment
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Regular Comment
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment: 'This PR is the bees knees!'

  test-json:
    name: Test Json
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set output
        id: set
        run: |
          echo 'theJSON<<EOF' >> $GITHUB_OUTPUT
          echo "$(cat ./test-assets/test.json)" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Test JSON Comment 1
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          json: ${{steps.set.outputs.theJson}}

      - name: Test JSON Commment 2
        uses: ./
        with:
          json: '{ "this": "pr", "is": "the", "bees": "knees"}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-file:
    name: Test File
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test File Commment
        uses: ./
        with:
          file_path: './test-assets/test.md'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
